export const SEARCH_RESTAURANTS = 'SEARCH_RESTAURANTS';
export const FILTER_RESTAURANTS = 'FILTER_RESTAURANTS';
export const ALL_RESTAURANTS = 'ALL_RESTAURANTS';
export const SET_LOADING = 'SET_LOADING';
export const SET_TEXT1 = 'SET_TEXT1';
